<?php
// $Id$

/**
 * @file
 * A module implementing tweaks and misc Drupal API hooks.
 *
 */

/**
* Implements hook_menu()
*/
function furnitalia_tweaks_menu() {
	$items['contact/ajax'] = array (
		'page callback' => 'furnitalia_tweaks_contact_js',
		'access callback' => TRUE, 
		'type' => MENU_CALLBACK,
	);
	$items['user/%user/favorites'] = array(
		'title' => 'My Favorites',
	    'page callback' => 'furnitalia_tweaks_favorites_list',
	    'access callback' => 'user_is_logged_in',
	    'type' => MENU_LOCAL_TASK,
    );
    $items['front'] = array (
		'page callback' => 'furnitalia_tweaks_front_page',
		'access callback' => TRUE, 
		'type' => MENU_CALLBACK,
	);
	$items['products/ajax'] = array (
		'page callback' => 'furnitalia_tweaks_products_ajax',
		'access callback' => TRUE, 
		'type' => MENU_CALLBACK,
	);
	
	return $items;
}

/**
 * Implements hook_menu_alter().
 */
function furnitalia_tweaks_menu_alter(&$items) {
	$items['taxonomy/term/%taxonomy_term']['page callback'] = 'furnitalia_tweaks_taxonomy_term_page';
	unset($items['taxonomy/term/%taxonomy_term']['file']);
	
	if(isset($items['user/%user/shortcuts'])) {
		unset($items['user/%user/shortcuts']);
	}
	
	if(isset($items['user/%user/imce'])) {
		unset($items['user/%user/imce']);	
	}
	
}

/**
 * Menu callback; displays all nodes associated with a term.
 *
 * @param $term
 *   The taxonomy term.
 * @return
 *   The page content.
 */
function furnitalia_tweaks_taxonomy_term_page($term) {
  // If there is a menu link to this term, the link becomes the last part of
  // the active trail, and the link name becomes the page title. Thus, we must
  // explicitly set the page title to be the term title.
  drupal_set_title($term->name);

  // Build breadcrumb based on the hierarchy of the term.
  $current = (object) array(
    'tid' => $term->tid,
  );  

  // Set the term path as the canonical URL to prevent duplicate content.
  $uri = entity_uri('taxonomy_term', $term);
  drupal_add_html_head_link(array('rel' => 'canonical', 'href' => url($uri['path'], $uri['options'])), TRUE);
  // Set the non-aliased path as a default shortlink.
  drupal_add_html_head_link(array('rel' => 'shortlink', 'href' => url($uri['path'], array_merge($uri['options'], array('alias' => TRUE)))), TRUE);

  // Normally we would call taxonomy_term_show() here, but for backwards
  // compatibility in Drupal 7 we do not want to do that (it produces different
  // data structures and HTML markup than what Drupal 7 released with). Calling
  // taxonomy_term_view() directly provides essentially the same thing, but
  // allows us to wrap the rendered term in our desired array structure.
  $build['term_heading'] = array(
    '#prefix' => '<div class="term-listing-heading">',
    '#suffix' => '</div>',
    'term' => taxonomy_term_view($term, 'full'),
  );

  if ($nids = taxonomy_select_nodes($term->tid, TRUE, variable_get('default_nodes_main', 10))) {
    $nodes = node_load_multiple($nids);
    //dsm($nodes);
    
    $build += furnitalia_tweaks_prepare_node_attributes($nodes);
    
  }
  else {
    $build['no_content'] = array(
      '#prefix' => '<p>',
      '#markup' => t('There is currently no content classified with this term.'),
      '#suffix' => '</p>',
    );
  }
  return $build;
}

/**
 * Construct a drupal_render() style array from an array of loaded nodes.
 *
 * @param $nodes
 *   An array of nodes as returned by node_load_multiple().
 * @param $view_mode
 *   View mode, e.g. 'full', 'teaser'...
 * @param $weight
 *   An integer representing the weight of the first node in the list.
 * @param $langcode
 *   (optional) A language code to use for rendering. Defaults to the global
 *   content language of the current request.
 *
 * @return
 *   An array in the format expected by drupal_render().
 */
function furnitalia_tweaks_node_view_multiple($nodes, $view_mode = 'teaser', $weight = 0, $langcode = NULL) {
  field_attach_prepare_view('node', $nodes, $view_mode, $langcode);
  entity_prepare_view('node', $nodes, $langcode);
  $build = array();
  foreach ($nodes as $node) {
  	$node->index = $weight + 1;
    $build['nodes'][$node->nid] = node_view($node, $view_mode, $langcode);
    $build['nodes'][$node->nid]['#weight'] = $weight;
    $weight++;
  }
  $build['nodes']['#prefix'] = '<div id="gallery-container">';
  $build['nodes']['#suffix'] = '</div>';
  $build['nodes']['#sorted'] = TRUE;
  return $build;
}

/**
 * Implements hook_page_alter().
 */
function furnitalia_tweaks_page_alter(&$page) {


	$page['left']['furn_menu'] = array(
		'#prefix' => '<nav id="main-nav">',
		'#suffix' => '</nav>',
	);
	  
	$result = db_query("
	  SELECT DISTINCT td.tid, td.name, h.parent as parent_term FROM {taxonomy_term_data} td
	  LEFT JOIN {taxonomy_index} tn on tn.tid = td.tid
	  LEFT JOIN {node} n on n.nid=tn.nid and n.status=1
	  INNER JOIN {taxonomy_term_hierarchy} h on td.tid=h.tid
	  WHERE td.vid = :vid", array(":vid" => 2));

	$items = array();
	foreach($result as $term) {
	
		$attributes = array();
		$active_attribute = array('class' => array('active'));
		
		if ($term->parent_term != 0 && !isset($items[$term->parent_term])) {
			
			if (furnitalia_tweaks_is_link_active($term->parent_term)) {
				$attributes = $active_attribute;
			}
			
			$parent_term = taxonomy_term_load($term->parent_term);
			$tems[$term->parent_term] = l($parent_term->name, 'taxonomy/term/' . $term->parent_term, array('attributes' => $attributes));
			
		} else if($term->parent_term == 0 && !isset($items[$term->tid])) {
		
			if (furnitalia_tweaks_is_link_active($term->tid)) {
				$attributes = $active_attribute;
			}

			$items[$term->tid] = l($term->name, 'taxonomy/term/' . $term->tid, array('attributes' => $attributes));
		}
		
	}


	$page['left']['furn_menu']['all'] = array(
		'#prefix' => '<h3><a id="bg1" href="#">All Collections</a></h3><div>',
		'#suffix' => '</div>',
		'#theme' => 'item_list',
		'#items' => $items,
		'#type' => 'ul',
		'#attributes' => array('class' => 'links'),
	);
	
	
	$editions = 22;
	$italia = 21;
	$result = db_query("
	  SELECT DISTINCT td.tid, td.name, b.field_brand_tid as brand, h.parent as parent_term FROM {taxonomy_term_data} td
	  LEFT JOIN {taxonomy_index} tn on tn.tid = td.tid
	  LEFT JOIN {node} n on n.nid=tn.nid and n.status=1
	  LEFT JOIN {taxonomy_term_hierarchy} h on td.tid=h.tid
	  INNER JOIN {field_data_field_brand} b on b.entity_id=n.nid and b.field_brand_tid IN(:brand1, :brand2)
	  WHERE td.vid = :vid", array(":brand1" => $italia, ":brand2" => $editions,":vid" => 2));
	  
	$italia_items = array();
	$editions_items = array();
	foreach($result as $term) {
		if	($term->brand == $italia) {
			if ($term->parent_term != 0 && !isset($italia_items[$term->parent_term])) {
				$parent_term = taxonomy_term_load($term->parent_term);
				$italia_items[$term->parent_term] = l($parent_term->name, 'taxonomy/term/' . $term->parent_term, array('query' => array('brand' => $italia)));
			} else if($term->parent_term == 0 && !isset($italia_items[$term->tid])) {
				$italia_items[$term->tid] = l($term->name, 'taxonomy/term/' . $term->tid, array('query' => array('brand' => $italia)));;				
			}
		} else {
			if ($term->parent_term != 0 && !isset($editions_items[$term->parent_term])) {
				$parent_term = taxonomy_term_load($term->parent_term);
				$editions_items[$term->parent_term] = l($parent_term->name, 'taxonomy/term/' . $term->parent_term, array('query' => array('brand' => $editions)));
			} else if($term->parent_term == 0 && !isset($editions_items[$term->tid])) {
				$editions_items[$term->tid] = l($term->name, 'taxonomy/term/' . $term->tid, array('query' => array('brand' => $editions)));				
			}
		}
	}

	$page['left']['furn_menu']['italia'] = array(
		'#prefix' => '<h3><a id="bg2" href="#">Natuzzi Italia</a></h3><div>',
		'#suffix' => '</div>',
		'#theme' => 'item_list',
		'#items' => array_values($italia_items),
		'#type' => 'ul',
		'#attributes' => array('class' => 'links'),
	);
	
	$page['left']['furn_menu']['editions'] = array(
		'#prefix' => '<h3><a id="bg3" href="#">Natuzzi Editions</a></h3><div>',
		'#suffix' => '</div>',
		'#theme' => 'item_list',
		'#items' => array_values($editions_items),
		'#type' => 'ul',
		'#attributes' => array('class' => 'links'),
	);
	
	$page['left']['furn_menu']['interior_design'] = array(
		'#prefix' => '<h3><a id="bg4" href="#">Interior Design</a></h3><div>',
		'#suffix' => '</div>',
	);

	
	/*$result = db_query("
	  SELECT DISTINCT td.tid, td.name FROM {taxonomy_term_data} td
	  INNER JOIN {taxonomy_term_hierarchy} h on td.tid=h.tid and h.parent=:parent_cat
	  LEFT JOIN {taxonomy_index} tn on tn.tid = td.tid
	  LEFT JOIN {node} n on n.nid=tn.nid and n.status=1
	  INNER JOIN {field_data_field_brand} b on b.entity_id=n.nid and b.field_brand_tid=:brand
	  WHERE td.vid = :vid", array(":parent_cat" => 1, ":brand" => 21, ":vid" => 2));	*/
	  
	$result = db_query("
	  SELECT DISTINCT td.tid, td.name FROM {taxonomy_term_data} td
	  INNER JOIN {taxonomy_term_hierarchy} h on td.tid=h.tid and h.parent=:parent_cat
	  LEFT JOIN {taxonomy_index} tn on tn.tid = td.tid
	  LEFT JOIN {node} n on n.nid=tn.nid and n.status=1
	  WHERE td.vid = :vid", array(":parent_cat" => 1, ":vid" => 2));
	

	$items = array();
	foreach($result as $term) {
	  $items[] = l($term->name, 'taxonomy/term/' . $term->tid);
	}

	$page['content_top']['furn_top_menu'] = array(
		'#theme' => 'item_list',
		'#items' => $items,
		'#type' => 'ul',
		'#attributes' => array('class' => 'links inline'),
	);
	
	//dsm($page);
	if (isset($page['content']['system_main']['options'])) {
		$page['left']['options'] = $page['content']['system_main']['options'];
		unset($page['content']['system_main']['options']);		
	}
}

function furnitalia_tweaks_is_link_active($tid, $query = NULL) {
	if ( arg(0) == 'taxonomy' && arg(1) == 'term') {
		if (is_numeric(arg(2)) && (arg(2) == $tid || furnitalia_tweaks_is_child(arg(2), $tid))) {
			return TRUE;
		}
	}
	
	return FALSE;
	
}

function furnitalia_tweaks_is_child($first_tid, $second_tid) {
	$parents = taxonomy_get_parents($first_tid);
	
	foreach($parents as $parent_term) {
		if ($parent_term->tid == $second_tid) {
			return true;
		}
	}
	
	return false;
}

function furnitalia_tweaks_form_alter(&$form, &$form_state, $form_id){
	if ($form['#id'] == 'item-node-form') {
		//dsm($form);
		
		//place video field in tabs
	    $form['item_video'] = array(
	        '#type' => 'fieldset',
	        '#title' => t('Item Video'),
	        '#collapsible' => TRUE,
	        '#collapsed' => FALSE,
	        '#group' => 'additional_settings',
	        '#weight' => -2, //Tab location
	    );
	    $form['item_video']['und'][0] = $form['field_video'];
	    unset($form['field_video']);
	    
	    $form['buttons']['#weight'] = 100;
	    
	    //put field ALU in product info
	    $form['base']['field_alu'] = $form['field_alu']['und'][0];
		$form['base']['field_alu']['#weight'] = 1;
		
		//put sale price in product info
		$form['field_sale_price']['und'][0]['value']['#attributes'] = array('size'=> array("15"));
		$form['field_sale_price']['und'][0]['value']['#default_value'] = 0;
		$form['base']['prices']['field_sale_price'] = $form['field_sale_price'];
		$form['base']['prices']['list_price']['#title'] = "MSRP";
		$form['base']['prices']['sell_price']['#title'] = "Furnitalia";
		
		//unset old values
		unset($form['base']['prices']['cost']);
		unset($form['base']['pkg_qty']);
		unset($form['base']['ordering']);		
	    unset($form['field_sale_price']);
		unset($form['field_alu']);
		unset($form['revision_information']);
		unset($form['author']);		

    }
}

/**
 * Display the list of items that are in current user's favorites list
 */
function furnitalia_tweaks_favorites_list() {
	global $user;
	
	$favorites = flag_get_user_flags('node', NULL, $user->uid);
	
	if(!isset($favorites['favorites']) || empty($favorites['favorites'])) {
		return "Your favorites list is empty. You can add items to favorites by clicking on 'Add to favorites' button on item info page";
	}
	
	$nids = array();
	
	foreach($favorites['favorites'] as $nid => $flag_obj) {
		$nids []= $nid;
	}
	
	dsm($favorites);
	
	$nodes = node_load_multiple($nids);    
    $build = furnitalia_tweaks_prepare_node_attributes($nodes);
    
    unset($build['options']);

	
	//print flag_create_link('favorites', $node->nid); 
	
	return $build;
}

/**
  * Display contact form in pop-up dialog box.
 */
function furnitalia_tweaks_contact_js($nid=NULL){

	$nid = 32;

	$output = "";
	$node = node_load($nid);
	$output .= theme('node', node_view($node));
	
	//return drupal_json_output(array('status' => TRUE, 'data' => $output, 'wrapperID' => drupal_html_id('webform-ajax-wrapper-' . $nid)));
	//ajax_command_replace('#dialog-form', $output), 	
	//$output = array('#type' => 'ajax', '#commands' => array(array('command' => 'openPopup', 'data' => $output)));
	
	ajax_deliver(array('#type' => 'ajax', '#commands' => array(
		array(
			'command' => 'openPopup', 
			'data' => $output,
			'method' => 'html',
		    'selector' => "#dialog-form",
		    'settings' => NULL,
		),
		//ajax_command_replace('#pagination', $output), 
	)));
	
	//return array('#type' => 'ajax', '#commands' => array(
	//	ajax_command_replace('#pagination', $output), 
	//));
    
}

function  furnitalia_tweaks_prepare_node_attributes($nodes) {
	
	if (!is_array($nodes)) {
		return array();
	}

    $build += furnitalia_tweaks_node_view_multiple($nodes);

	return $build;
	
}

function furnitalia_tweaks_webform_submission_presave($node, &$submission) {	
	
	if ($node->nid == 32) {
		
		$first_name = $submission->data[1]['value'][0];
		$last_name = $submission->data[2]['value'][0];		
		$email = $submission->data[3]['value'][0];
		$text = $submission->data[4]['value'][0];
		
	}

	/*$submission_array = array();

	$submission_array['oid'] = '00D80000000Jw8P';
	$submission_array['sfga'] = '00D80000000Jw8P';

	if ($submission->nid == 52) { // Request info page
		$submission_array['first_name'] = $submission->data[1]['value'][0];
		$submission_array['last_name'] = $submission->data[6]['value'][0];
		$submission_array['email'] = $submission->data[2]['value'][0];
		$submission_array['phone'] = $submission->data[3]['value'][0];	   
		$submission_array['00N80000002Z2Pz'] = $submission->data[5]['value'][0]; //item
		$description = str_replace("\r\n", " ", $submission->data[4]['value'][0]); //question
		$description = str_replace("''", "in", $description);
		$description = str_replace("'", "", $description);
		$description = str_replace("\"", "", $description);
		$description = strip_tags($description);
		$submission_array['description'] = $description;
	}
	else if ($submission->nid == 157) { // contact us page
		$submission_array['first_name'] = $submission->data[1]['value'][0];
		$submission_array['last_name'] = $submission->data[5]['value'][0];
		$submission_array['email'] = $submission->data[2]['value'][0];
		$submission_array['00N80000002Z2Pz'] = $submission->data[3]['value'][0]; //subject
		$description = str_replace("\r\n", " ", check_plain($submission->data[4]['value'][0])); //body
		$description = str_replace("''", "in", $description);
		$description = str_replace("'", "", $description);
		$description = str_replace("\"", "", $description);
		$description = strip_tags($description);
		$submission_array['description'] = $description;
	}

	$querystring = "";
	foreach($submission_array as $key => $val) {
		$querystring .= "$key=". decode_entities(strip_tags($val));
		$querystring .= "&";
	}

	$URL="www.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8";
	$ch = curl_init();   
	curl_setopt($ch, CURLOPT_URL,"https://$URL"); 
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "$querystring");
	curl_exec ($ch);    
	curl_close ($ch);
  
  if ($submission->nid == 157) {
    watchdog("Furnitalia", "Contact Us submission saved: " . $submission->data[3]['value'][0], array(), WATCHDOG_INFO, null);
  } else if ($submission->nid == 52) {
    watchdog("Furnitalia", "Request submission saved: " . $submission->data[5]['value'][0], array(), WATCHDOG_INFO, null);
  }*/
}

/**
  * Displays front page content for Furntialia website
 */
function furnitalia_tweaks_front_page() {
	drupal_add_js(drupal_get_path('theme', 'furnitheme') . "/js/jquery.bgpos.js");
	drupal_add_js(drupal_get_path('theme', 'furnitheme') . "/js/frontpage.js");
	drupal_add_library('system', 'drupal.ajax');
	
	//$sofas_term = taxonomy_term_load(2);
	
	$build = array();
	
	//$build += furnitalia_tweaks_taxonomy_term_page($sofas_term);

	$build['category-preview'] = array(
		'#markup' => '<div id="cat-preview">					
						<div id="category-image-pane">
					  		<a href="#" class="category1 category-image" style="display:block"><img src="' .drupal_get_path('theme', 'furnitheme') . "/images/category-image-1.jpg" . '" title="Furnitalia collections"  /></a>
					  		<a href="#" class="category2 category-image" ><img src="' .drupal_get_path('theme', 'furnitheme') . "/images/category-image-2.jpg" . '" title="Furnitalia collections" /></a>
					  		<a href="#" class="category3 category-image"><img src="' .drupal_get_path('theme', 'furnitheme') . "/images/category-image-3.jpg" . '" title="Furnitalia collections"  /></a>
					  		<a href="#" class="category4 category-image"><img src="' .drupal_get_path('theme', 'furnitheme') . "/images/category-image-4.jpg" . '" title="Furnitalia collections"  /></a>
					  	</div>
 				  	 </div>',
	);
	
	$build['front-anim'] = array (
		'#markup' => '<div id="front-overlay">
						<div id="front-left">&nbsp;</div>
						<div id="front-right"><a href="#" id="enterFurnitalia">ENTER FURNITALIA</a></div>						
						<div id="menu-pic-wrapper">
					  		<div id="menu-pic" class="menu-hover loading">&nbsp;</div>
					  	</div>
 				  	 </div>',
	);
	
	drupal_set_title("Modern Furniture Store Sacramento/Roseville");
	
	return $build;
}

/**
  * AJAX callback for products (gallery) page
 */
function furnitalia_tweaks_products_ajax () {
	
	ajax_deliver(array('#type' => 'ajax', '#commands' => array(
		array(
			'command' => 'openPopup', 
			'data' => $output,
			'method' => 'html',
		    'selector' => "#dialog-form",
		    'settings' => NULL,
		),
		//ajax_command_replace('#pagination', $output), 
	)));
}