<?php

/**
 * Implements hook_menu().
 */
function furnileads_menu() {
	$items = array();
	
	$items['admin/leads'] = array(
		'title' => 'Furnitalia Leads',
		'description' => 'Furnitalia Leads Control Panel.',
		'page callback' => 'furnileads_page',
		'access callback' => 'user_access',
		'access arguments' => array('administer leads'),
	);
	
	$items['admin/leads/list'] = array(
		'title' => 'View Leads',
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => -1,
	);
	$items['admin/leads/add'] = array(
		'title' => 'Add Lead',
		'description' => 'Furnitalia Leads Control Panel.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('furnileads_lead_edit_form'),
		'type' => MENU_LOCAL_TASK,
		'access callback' => 'user_access',
		'access arguments' => array('administer leads'),
	);
	$items['admin/leads/%lead'] = array(
		'title' => 'View Lead Information',
		'description' => 'Furnitalia Leads Control Panel.',
		'page callback' => 'furnileads_lead_detail_page',
		'page arguments' => array(2),
		'type' => MENU_CALLBACK,
		'access callback' => 'user_access',
		'access arguments' => array('administer leads'),
	);
	$items['admin/leads/%lead/view'] = array(
		'title' => 'View',
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => -1,
	);
	$items['admin/leads/%lead/edit'] = array(
		'title' => 'Edit Lead',
		'description' => 'Furnitalia Leads Control Panel.',
		'page callback' => 'furnileads_lead_detail_edit_page',
		'page arguments' => array(2),
		'type' => MENU_LOCAL_TASK,
		'access callback' => 'user_access',
		'access arguments' => array('administer leads'),
	);
	$items['admin/leads/xmlrpc'] = array(
		'title' => 'Furnitalia Leads XMLRPC',
		'page callback' => 'furnileads_lead_xmlrpc_page',
		'type' => MENU_CALLBACK,
		'access callback' => 'user_access',
		'access arguments' => array('administer leads'),
	);

	return $items;
}

/**
 * Implements hook_admin_paths_alter().
 */
function furnileads_admin_paths_alter(&$paths) {
	$paths['admin/leads'] = TRUE;
	$paths['admin/leads/list'] = TRUE;
	$paths['admin/leads/add'] = TRUE;
	$paths['admin/leads/%lead'] = TRUE;	
}

/** 
 * Implements hook_load().
 */
function lead_load($lid) {
	$res = db_select('furnileads', 'fl')
		->fields('fl')
		->condition('lid', $lid)
		->execute();

	return $res->fetchObject();
}

/**
 * Implements hook_permission().
 */
function furnileads_permission() {
  return array(
    'administer leads' => array(
      'title' => t('Administer leads'),
      'description' => t('Perform administration on Furnitalia leads.'),
    ),
  );
}

/**
 * Display list of leads
 */
function furnileads_page() {

	$query = db_select('furnileads', 'f');
	$query->fields('f', array('status'));
	$query->addExpression('COUNT(f.lid)', 'lead_count');
	$query->groupBy('f.status');
	$result = $query->execute();
	$stats_info = "";
	$status_options = _get_lead_status_options();
	while($record = $result->fetchAssoc()) {
        $stats_info .= '<strong>' . $status_options[$record['status']] . ":</strong>" . " " .  $record['lead_count']  . "&nbsp;&nbsp;|&nbsp;&nbsp;";
    } 
	
	$query = db_select('furnileads', 'f');
	$query->fields('f', array('lid', 'status', 'created',  'first_name', 'last_name', 'body', 'updated_by', 'updated'));
	$query->addExpression('CASE WHEN f.status=\'N\' THEN 1 WHEN f.status=\'P\' THEN 2 WHEN f.status=\'S\' THEN 3 WHEN f.status=\'C\' THEN 4 ELSE 0 END', 'sort_col');
	$query->orderBy('sort_col', 'ASC');
	$query->orderBy('created', 'DESC');	
	$result = $query->extend('PagerDefault')->limit(50)->execute();

	$time_format = 'm-d-Y H:i';
	$rows = array(); 

	while(($lead = $result->fetchAssoc())) {
		$temp_row = array();

		switch ($lead['status']) {
			case 'N':
				$status_bg = "background-color:rgb(255, 130, 130);";
				$status_class = "open";
				$status_caption = "Open";
				break;
			case 'P':
				$status_bg = "background-color:rgb(253, 235, 117);";
				$status_class = "pending";			
				$status_caption = "Pending";
				break;
			case 'S':
				$status_bg = "background-color:rgb(160, 236, 111);";
				$status_class = "sold";
				$status_caption = "Sold";				
				break;				
			case 'C':
				$status_bg = "background-color:rgb(90, 198, 255);";
				$status_class = "closed";
				$status_caption = "Closed";
				break;				
			default:
				$status_bg = "background-color:white;";
				$status_class = "";
				$status_caption = "Data Error";
				break;
		}
		
		$temp_row['status'] = array('data' => $status_caption, 'style' => array($status_bg), 'class' => array($status_class));
		$temp_row['created'] = format_date($lead['created'], 'custom', $time_format); 
		$temp_row['lead_name'] = $lead['first_name'] . ' ' . $lead['last_name'];
		$temp_row['body'] = substr($lead['body'],0, 50).'...';

		$user = user_load($lead['updated_by']);
		$profile = field_get_items('user', $user, 'field_first_name');
		$user_name = $profile[0]['value'];

		$temp_row['updated_by'] = $user_name;
		$temp_row['updated'] = empty($lead['updated']) ? "" : format_date($lead['updated'], 'custom', $time_format);

		$temp_row['edit'] = l('View', 'admin/leads/' . $lead['lid']) . ' | ' . l('Edit', 'admin/leads/' . $lead['lid'] . '/edit');

		$rows []= $temp_row;
	}

	$header = array('Status', 'Created', 'Lead Name', 'Body', 'Lead owner', 'Last action', 'Actions');

	//show lead statistics
	$output['stats'] = array(
		'#prefix' => '<div id="lead-stats" style="border:2px solid #981b1e; padding:1em; margin-bottom:1em;">',
		'#markup' => $stats_info,
		'#suffix' => '</div>',
	);
	
	//output results as table
	$output['rows'] = array(
		'#theme' => 'table',
		'#header' => $header,
		'#rows' => $rows,
	);
	
	//add pager to the bottom
	$output['pager'] = array(
		'#markup' => theme('pager', array('tags' => array()))
	);
	
	return $output;
}

/**
 * Display edit form for a selected lead.
 */
function furnileads_lead_detail_edit_page($lead) {
	if (!$lead) {
		return drupal_not_found();
	}

	drupal_set_title('Edit Lead Information');
	furnileads_set_breadcrumb();

	$output = drupal_get_form('furnileads_lead_edit_form', $lead);

	return $output;
}

/**
 * Display details for a selected lead.
 */
function furnileads_lead_detail_page($lead) {
	if (!$lead) {
		return drupal_not_found();
	}
	
	drupal_set_title('View Lead Details');
	furnileads_set_breadcrumb();
	
	$output = drupal_get_form('furnileads_lead_form', $lead);

	return $output;
}

/**
 * Implements hook_form().
 */
function furnileads_lead_form($form, &$form_state, $lead) {

	drupal_add_css(drupal_get_path('theme', 'furnitheme') . '/css/leads.css');

	$user = user_load($lead->updated_by);
	$profile = field_get_items('user', $user, 'field_first_name');
	$user_name = $profile[0]['value'];

	$time_format = 'm-d-Y H:i';

	$form =array();

	$form['created'] = array(
		'#prefix' => '<div>',
		'#markup' => 'Created: ' . format_date($lead->created, 'custom', $time_format), 
		'#suffix' => '</div>',
	);

	$form['status_wrapper'] = array(
		'#type' => 'fieldset',
		'#title' => 'Status',
	);
	$form['status_wrapper']['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#options' => _get_lead_status_options(),
		'#default_value' => $lead->status,
	);
	
	$form['status_wrapper']['type'] = array(
		'#type' => 'select',
		'#title' => t('Lead type'),
		'#options' => _get_lead_types(),
		'#default_value' => $lead->type,
	);
	$form['status_wrapper']['updated'] = array(
		'#prefix' => '<div>',
		'#markup' => '<strong>' . t('Last updated') . ": </strong>" .  (empty($lead->updated) ? 'N/A' : format_date($lead->updated, 'custom', $time_format)),
		'#suffix' => '</div>',
	);
	$form['status_wrapper']['updated_by'] = array(
		'#prefix' => '<div>',
		'#markup' => '<strong>' . t('Lead owner') . ": </strong>" . (empty($lead->updated_by) ? 'N/A' : $user_name), 
		'#suffix' => '</div>',
	);
	
	$form['status_wrapper']['status_comments'] = array(
		'#type' => 'textarea',
		'#title' => t('Status & comments'),
		'#default_value' => $lead->status_comments,
		'#cols' => '40',
		'#rows' => '4',
	);

		
	$form['first_name'] = array(
		'#type' => 'textfield',
		'#disabled' => TRUE,
		'#title' => t('First name'),
		'#default_value' => $lead->first_name,
		'#size' => '40' ,
		'#maxlength' => 128,
		'#required' => TRUE,
	);
	$form['last_name'] = array(
		'#type' => 'textfield',
		'#disabled' => TRUE,
		'#title' => t('Last name'),
		'#default_value' => $lead->last_name,
		'#size' => '40' ,
		'#maxlength' => 128,
		'#required' => TRUE,
	);
	$form['email'] = array(
		'#type' => 'textfield',
		'#disabled' => TRUE,		
		'#title' => t('Email'),
		'#default_value' => $lead->email,
		'#size' => '40' ,
		'#maxlength' => 128,
		'#required' => TRUE,
	);
	$form['phone'] = array(
		'#type' => 'textfield',
		'#disabled' => TRUE,		
		'#title' => t('Phone'),
		'#default_value' => $lead->phone,
		'#size' => '15' ,
		'#maxlength' => 20,
	);
	$form['zip'] = array(
		'#type' => 'textfield',
		'#disabled' => TRUE,		
		'#title' => t('ZIP'),
		'#default_value' => $lead->zip,
		'#size' => '7' ,
		'#maxlength' => 7,
	);
	$form['address'] = array(
		'#type' => 'textfield',
		'#disabled' => TRUE,		
		'#title' => t('Address'),
		'#default_value' => $lead->address,
		'#size' => '50' ,
		'#maxlength' => 255,
	);
	$form['body'] = array(
		'#type' => 'textarea',
		'#disabled' => TRUE,		
		'#title' => t('Message'),
		'#default_value' => $lead->body,
		'#cols' => '40',
		'#rows' => '4',
	);
	
	//wrap around container
	$form = array('lead' => $form);
	$form['lead']['#type'] = 'fieldset';
	$form['lead']['#title'] = 'Lead Info';
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);
	$form['#submit'][] = 'furnileads_lead_edit_form_submit';

	return $form;
}

/**
 * Implements hook_form().
 */
function furnileads_lead_edit_form($form, &$form_state, $lead=NULL) {

	drupal_add_css(drupal_get_path('theme', 'furnitheme') . '/css/leads.css');

	$new_lead = FALSE;
	if (isset($lead)) {
		$user = user_load($lead->updated_by);
		$profile = field_get_items('user', $user, 'field_first_name');
		$user_name = $profile[0]['value'];

	} else {
		$lead = new stdClass;
		$lead->type = 'R';
		$lead->first_name = '';
		$lead->last_name = '';
		$lead->email = '';
		$lead->address = '';
		$lead->phone = '';
		$lead->body = '';
		$lead->status = 'N';
		$lead->zip = '';
		$new_lead = TRUE;
	}

	$time_format = 'm-d-Y H:i';

	$form =array();

	if (!$new_lead) {
		$form['created'] = array(
			'#prefix' => '<div>',
			'#markup' => 'Created: ' . format_date($lead->created, 'custom', $time_format), 
			'#suffix' => '</div>',
		);
	}
	
	$form['status_wrapper'] = array(
		'#type' => 'fieldset',
		'#title' => 'Status',
	);
	$form['status_wrapper']['status'] = array(
		'#type' => 'select',
		'#title' => t('Status'),
		'#options' => _get_lead_status_options(),
		'#default_value' => $lead->status,
	);
	
	$form['status_wrapper']['type'] = array(
		'#type' => 'select',
		'#title' => t('Lead type'),
		'#options' => _get_lead_types(),
		'#default_value' => $lead->type,
	);

	
	if(!$new_lead) {
		$form['status_wrapper']['updated'] = array(
			'#prefix' => '<div>',
			'#markup' => '<strong>' . t('Last updated') . ": </strong>" .  (empty($lead->updated) ? 'N/A' : format_date($lead->updated, 'custom', $time_format)),
			'#suffix' => '</div>',
		);
		$form['status_wrapper']['updated_by'] = array(
			'#prefix' => '<div>',
			'#markup' => '<strong>' . t('Lead owner') . ": </strong>" . (empty($lead->updated_by) ? 'N/A' : $user_name), 
			'#suffix' => '</div>',
		);
		
		$form['status_wrapper']['status_comments'] = array(
			'#type' => 'textarea',
			'#title' => t('Status & comments'),
			'#default_value' => $lead->status_comments,
			'#cols' => '40',
			'#rows' => '4',
		);
	}
	$form['first_name'] = array(
		'#type' => 'textfield',
		'#title' => t('First name'),
		'#default_value' => $lead->first_name,
		'#size' => '40' ,
		'#maxlength' => 128,
		'#required' => TRUE,
	);
	$form['last_name'] = array(
		'#type' => 'textfield',
		'#title' => t('Last name'),
		'#default_value' => $lead->last_name,
		'#size' => '40' ,
		'#maxlength' => 128,
		'#required' => TRUE,
	);
	$form['email'] = array(
		'#type' => 'textfield',
		'#title' => t('Email'),
		'#default_value' => $lead->email,
		'#size' => '40' ,
		'#maxlength' => 128,
		'#required' => TRUE,		
	);
	$form['phone'] = array(
		'#type' => 'textfield',
		'#title' => t('Phone'),
		'#default_value' => $lead->phone,
		'#size' => '15' ,
		'#maxlength' => 20,
	);
	$form['zip'] = array(
		'#type' => 'textfield',		
		'#title' => t('ZIP'),
		'#default_value' => $lead->zip,
		'#size' => '7' ,
		'#maxlength' => 7,
	);
	$form['address'] = array(
		'#type' => 'textfield',
		'#title' => t('Address'),
		'#default_value' => $lead->address,
		'#size' => '50' ,
		'#maxlength' => 255,
	);
	
	$form['body'] = array(
		'#type' => 'textarea',
		'#title' => t('Message'),
		'#default_value' => $lead->body,
		'#cols' => '40',
		'#rows' => '4',
	);
	
	
	//wrap around container
	$form = array('lead' => $form);
	$form['lead']['#type'] = 'fieldset';
	$form['lead']['#title'] = 'Lead Info';
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Save'),
	);
	
	if (!$new_lead) { // && _is_admin()) {
		//delete button
		$form['delete'] = array(
			'#type' => 'button',
			'#value' => t('Delete Lead'),
			'#executes_submit_callback' => TRUE,
		);
	}

	return $form;
}

/**
  * Implements hook_submit().
 */
function furnileads_lead_edit_form_submit($form, &$form_state) {
	//dsm($form_state);
	global $user;

	$lead = $form_state['values'];

	if(count($form_state['build_info']['args']) > 0 ) {
		$lid = $form_state['build_info']['args'][0]->lid;
		if (is_numeric($lid)) {
			
			if (strtolower($form_state['clicked_button']['#value']) == 'save') { 
				$lead['lid'] = $lid;
				$lead['updated_by'] = $user->uid;
				$lead['updated'] = REQUEST_TIME;
				
				db_update('furnileads')
					->fields(array(
						'updated' => $lead['updated'],
						'updated_by' => $lead['updated_by'],
						'type' => $lead['type'],
						'first_name' => $lead['first_name'],
						'last_name' => $lead['last_name'],
						'email' => $lead['email'],
						'phone' => $lead['phone'],
						'address' => $lead['address'],
						'body' => $lead['body'],
						'status' => $lead['status'],
						'status_comments' => $lead['status_comments'],
						'zip' => $lead['zip'],
					 ))
					->condition('lid', $lid)
					->execute();
	
				drupal_set_message('Changes for lead ' . $lead['first_name'] . ' ' . $lead['last_name']. ' were saved');
			
			} else {
				if (furnileads_delete_lead($lid)) {
					drupal_set_message('Lead ' . $lead['email'] . ' deleted.');	
				} else {
					drupal_set_message('Error deleting lead ' . $lead['email'] . '.');	
				}
			}
			
			drupal_goto("admin/leads");


		} else {
			drupal_set_message("Changes to lead info were not saved. Missing lead ID.", "error");
			drupal_goto("admin/leads");
		}
	} else {
		
		//create a new lead
		$lead['updated_by'] = 0;//$user->uid;
		$lead['created'] = REQUEST_TIME;
		$lead['updated'] = 0;//REQUEST_TIME;
		$lead['status_comments'] = '';
		$lid = furnileads_insert_lead($lead);
		/*
if (is_numeric($lid)) {
			drupal_set_message("Lead record was created");
			drupal_goto("admin/leads/$lid");
		}
*/
		drupal_goto("admin/leads");
	}
	
}


/**
 * Insert lead record.
 */
function furnileads_insert_lead($lead) {
	if (!is_array($lead)) {
		drupal_set_message("Error saving lead record.");
		return;
	}

	$lid = db_insert('furnileads')
		->fields(array(
 			 'created',
			 'updated',
			 'updated_by',
			 'type',
			 'first_name',
			 'last_name',
			 'email',
			 'phone',
			 'address',
			 'body',
			 'status',
			 'status_comments',
			 'zip',
		 ))
		->values(array(
			 $lead['created'],
			 $lead['updated'],
			 $lead['updated_by'],
			 $lead['type'],
			 $lead['first_name'],
			 $lead['last_name'],
			 $lead['email'],
			 $lead['phone'],
			 $lead['address'],
			 $lead['body'],
			 $lead['status'],
			 $lead['status_comments'],
			 $lead['zip'],
		))
		->execute();

	return $lid;
}

/**
 * Insert lead record.
 */
function furnileads_delete_lead($lid) {
	if (!is_numeric($lid)) {
		drupal_set_message("Invalid lead ID specified.");
		return;
	}

	$num_deleted = db_delete('furnileads')->condition('lid', $lid)->execute();

	return $num_deleted;
}


/**
 * Implements hook_xmlrpc().
 *
 * Provides Drupal with an array to map XML-RPC callbacks to existing functions.
 * These functions may be defined in other modules. The example implementation
 * defines specific functions for the example services.
 *
 * Note: Drupal's built-in XML-RPC server already includes several methods by
 * default:
 *
 * Service dicovery methods:
 * - system.listMethods: return a list of the methods the server has, by name.
 * - system.methodSignature: return a description of the argument format a
 * - system.methodHelp: returns a text description of a particular method.
 *   particular method expects.
 *
 * Other:
 * - system.multicall: perform several method calls in a single xmlrpc request.
 * - system.getCapabilities: determine if a given capability is supported.
 *
 * The methods defined by hook_xmlrpc() will be added to those provided by
 * default by Drupal's XML-RPC server.
 *
 * @see hook_xmlrpc()
 */
function furnileads_xmlrpc() {
  $methods[] = array(
    // First argument is the method name.
    'furnileads.addlead',
    // Callback to execute when this method is requested.
    '_furnileads_xmlrpc_insert_lead',
    // An array defines the types of output and input values for this method.
    array(
       'string', 'array', 
    ),
    // Include a little description that is shown when XML-RPC server is
    // requested for the implemented methods list.
    // Method description.
    t('Creates a lead based on request submission data.'),
  );
  
  return $methods;
}

/**
 * This is the callback for the furnileads.addlead method.
 *
 * Saves lead information to database.
 *
 * @param $lead_info
 *   Array containing Lead information.
 *
 * @return
 *   If save is successful, returns link to view newly inserted lead.
 *
 * @see xmlrpc_error()
 */
function _furnileads_xmlrpc_insert_lead($lead_info) {
	
	global $base_url;
	
	if (!is_array($lead_info)) {
		return xmlrpc_error(10002, t('Input lead information must be array'));
	}
	
	if (!isset($lead_info['email'])) {
		return xmlrpc_error(10002, t('Missing mandatory lead email address'));		
	}
	
	$lead = array();
	$lead['type'] = isset($lead_info['type']) ? $lead_info['type'] : '';
	$lead['first_name'] = isset($lead_info['first_name']) ? $lead_info['first_name'] : '';	
	$lead['last_name'] = isset($lead_info['last_name']) ? $lead_info['last_name'] : '';	
	$lead['email'] = isset($lead_info['email']) ? $lead_info['email'] : '';	
	$lead['phone'] = isset($lead_info['phone']) ? $lead_info['phone'] : '';
	$lead['address'] = isset($lead_info['address']) ? $lead_info['address'] : '';
	$lead['body'] = isset($lead_info['body']) ? $lead_info['body'] : '';	
	
	//defaults
	$lead['created'] = REQUEST_TIME;
	$lead['updated'] = 0;
	$lead['updated_by'] = 0;
	$lead['status'] = 'N';
	$lead['status_comments'] = "";
	$lead['zip'] = "";
	
	$lid = furnileads_insert_lead($lead);
	
	if (is_numeric($lid)) {
		return url($base_url . '/admin/leads/' . $lid, array('external' => TRUE)); 
	} else {
		return xmlrpc_error(10002, t('Error saving lead information.'));	
	}
	
}

/** 
  * XMLRPC Client implementation
 */
/*
function furnileads_xmlrpc_client() {
  // First define the endpoint of the XML-RPC service, in this case is our
  // own server.
  global $base_url;
  $server = url($base_url . '/xmlrpc.php', array('external' => TRUE));
  
  $lead_info = array();
  $lead_info['first_name'] = 'Tester';	
  $lead_info['last_name'] = 'Unspecified';	
  $lead_info['email'] = 'somemail@domain.com';	
  $lead_info['phone'] = '916-999-000-00';
  $lead_info['address'] = 'PO Box 222222 Sacramento CA 05934';
  $lead_info['body'] = 'Please give me more info on this product.';	
	
  // Then we should define the method to call. xmlrpc() requires that all the
  // information related to the called method is passed as an array in the form
  // of 'method_name' => arguments_array
  $options = array(
    'furnileads.addlead' => array(
    	$lead_info,
    ),
  );
  
  // Make the xmlrpc request and process the results.
  $result = xmlrpc($server, $options);
  if ($result === FALSE) {
    drupal_set_message(
      t('Error return from xmlrpc(): Error: @errno, Message: @message',
      array('@errno' => xmlrpc_errno(), '@message' => xmlrpc_error_msg())),
      'error'
    );
  }
  else {
    drupal_set_message(
      t('The XML-RPC server returned this response: @response',
      array('@response' => print_r($result, TRUE)))
    );
  }
}

function furnileads_lead_xmlrpc_page() {
	furnileads_xmlrpc_client();
	return "This is a leads XMLRPC client";
}
*/

function _is_admin() {
	global $user;
	
	return $user->uid == 1;
}

function furnileads_set_breadcrumb() {
	// set the breadcrumb
	$breadcrumb = array();
	$breadcrumb[] = l('Home', '<front>');
	$breadcrumb[] = l('Furnitalia Leads', 'admin/leads');
    $breadcrumb[] = drupal_get_title();

	drupal_set_breadcrumb($breadcrumb);         
}


function _get_lead_status_options() {
	$lead_status_options = array(
		'N' => 'Open',
		'P' => 'Pending',
		'S' => 'Sold',
		'C' => 'Closed',
	);
	
	return $lead_status_options;
}

function _get_lead_types() {
	$lead_types = array(
		'R' => 'Request Product Info',
		'P' => 'Request Parts / Support',
		'S' => 'SPAM',
		'F' => 'Feedback',
	);
	
	return $lead_types;
}

/**
 * Implements hook_views_api().
 */
function furnileads_views_api() {
  return array(
    'api' => '2.0',
    'path' => drupal_get_path('module', 'furnileads') . '/views',
  );
}