<?php
// $Id$

/**
 * @file
 * A module implementing tweaks and misc Drupal API hooks.
 *
 */

/**
* Implements hook_menu()
*/
function mobile_tweaks_menu() {
	$items['contact/ajax'] = array (
		'page callback' => 'mobile_tweaks_contact_js',
		'access callback' => TRUE, 
		'type' => MENU_CALLBACK,
	);
	$items['request/%node/ajax'] = array (
		'page callback' => 'mobile_tweaks_contact_js',
		'page arguments' => array(1, '34'),
		'access callback' => TRUE, 
		'type' => MENU_CALLBACK,
	);
    $items['front'] = array (
		'page callback' => 'mobile_tweaks_front_page',
		'access callback' => TRUE, 
		'type' => MENU_CALLBACK,
	);
	$items['products/ajax'] = array (
		'page callback' => 'mobile_tweaks_products_ajax',
		'access callback' => TRUE, 
		'type' => MENU_CALLBACK,
	);
	
	return $items;
}

/**
 * Implements hook_form_alter
 *
 */
function mobile_tweaks_form_alter(&$form, &$form_state, $form_id){
	if ($form['#id'] == 'item-node-form') {
		
		//dsm($form);
		drupal_add_css(drupal_get_path('theme', 'furnitheme') . '/css/leads.css');

		//place video field in tabs
	    $form['item_video_container'] = array(
	        '#type' => 'fieldset',
	        '#title' => t('Item Video'),
	        '#collapsible' => TRUE,
	        '#collapsed' => FALSE,
	        '#group' => 'additional_settings',
	        '#weight' => -2, //Tab location
	    );

	    $form['field_video']['#container'] = array('field_video');	//make sure parent item doesn't change after moving form element
	    $form['item_video_container']['field_video'] = $form['field_video'];
	    unset($form['field_video']);	    
	    
	    $form['buttons']['#weight'] = 100;
	    
	    //put field ALU in product info
	    $form['base']['field_alu'] = $form['field_alu'];
		$form['base']['field_alu']['#weight'] = 1;
		
		//put 'display sale price' in product info
		$form['base']['prices']['field_display_sale_price'] = $form['field_display_sale_price'];
		unset($form['field_display_sale_price']);
		
		//put checkbox 'show add-to-cart button
		//$form['base']['show_add_to_cart'] = $form['field_show_add_to_cart'];
		//$form['base']['show_add_to_cart']['und']['#title'] = "Show 'Add to Cart' button?";
		//$form['base']['show_add_to_cart']['#weight'] = 2;
		
		//put sale price in product info
		$form['field_special_price']['und'][0]['value']['#attributes'] = array('size'=> array("15"));
		$form['base']['prices']['field_special_price'] = $form['field_special_price'];
		$form['base']['prices']['list_price']['#title'] = "MSRP";
		$form['base']['prices']['sell_price']['#title'] = "Furnitalia";
		
		//unset old values
		$form['base']['prices']['cost']['#access'] = FALSE;
		$form['base']['pkg_qty']['#access'] = FALSE;
		$form['base']['ordering']['#access'] = FALSE;		
	    unset($form['field_special_price']);
		$form['field_alu']['#access'] = FALSE;
		$form['revision_information']['#access'] = FALSE;
		$form['author']['#access'] = FALSE;
		//unset($form['field_show_add_to_cart']);
		
		//restrict title to be less than or equal to 20 characters
		$form['title']['#maxlength'] = '25';
		
    }
}

/**
  * Display contact form in pop-up dialog box.
 */
function mobile_tweaks_contact_js($item, $nid=NULL){

	if (!is_numeric($nid)) {
		$nid = 32; //contact us node id
	}

	$output = "";
	$node = node_load($nid);

	if ($nid == 34) { //request form
	
		#for request form, prepopulate item's name
		$node->webform['components'][5]['value'] = $item->title;
		$node->webform['components'][7]['value'] = $item->nid;
	}

	$node->title ="";
	$output .= theme('node', node_view($node));
	$output = '<h3 class="furn-ucase furn-red">REQUEST QUOTE</h3><div id="request-data">' . $output . '</div>';
	
	ajax_deliver(array('#type' => 'ajax', '#commands' => array (
		array(
			'command' => 'furnAjax', 
			'data' => $output,
			'method' => 'append',
		    'selector' => "#product-additional",
		    'settings' => NULL,
		),
	)));
    
}

/**
  * Displays front page content for Furntialia website
 */
function mobile_tweaks_front_page() {
	
	$build = array();
	
	drupal_set_title("Modern Furniture Store Sacramento/Roseville");

	$front_slides = "";
	$img_path = base_path() . "sites/default/files/promo/oct2014/";
	$imgs = array('320x420_MobileMain.jpg');
  $link = url(
    "living", 
    array(
      'query' => array(
        'availability' =>  'in_stock'
      )
    )
  );//array('utm_source' => 'mobile', 'utm_medium' => 'front', 'utm_campaign' => 'moving-sale')));
	foreach($imgs as $img) {
		$front_slides .= "<div class=\"slide\" data-mightyslider=\"cover: '" . $img_path . $img . "', link: {url:'" . $link . "'} \"></div>";
	}

	$front_gallery = <<<EOT
<div id="image-gallery" class="mightyslider_modern_skin horizontal no-pager">
	<div class="frame" style="overflow: hidden;" data-mightyslider="width:320,height:420">
		<div class="slide_element"> 
			$front_slides
		</div>		  				  		
	</div>
	<ul class="gal-pager mSPages"></ul>
</div>
EOT;
	
	$build['category-preview'] = array(
		'#markup' => $front_gallery, 
	);

	return $build;
}

/**
  * AJAX callback for products (gallery) page
 */
function mobile_tweaks_products_ajax () {
	
	ajax_deliver(array('#type' => 'ajax', '#commands' => array(
		array(
			'command' => 'openPopup', 
			'data' => $output,
			'method' => 'html',
		    'selector' => "#dialog-form",
		    'settings' => NULL,
		),
		//ajax_command_replace('#pagination', $output), 
	)));
}
